name = "gulid"
version = "0.0.7"

description = "ULID implementation in Gleam (Erlang target only)"
licences = ["Apache-2.0"]
repository = { type = "github", user = "vtomilin", repo = "gulid" }
# internal_modules = [
# "examples/*",
# ]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_crypto = ">= 1.3.0 and < 2.0.0"
gleam_erlang = ">= 0.26.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"